spring:
  cloud:
    gateway:
      routes:
      - id: bs-service-goods
        uri: lb://BS-SERVICE-GOODS
        predicates:
        - Path=/goods/**
      - id: bs-service-goods
        uri: lb://BS-SERVICE-MANAGER
        predicates:
        - Path=/manager/**
      - id: bs-service-user
        uri: lb://BS-SERVICE-USER
        predicates:
        - Path=/user/**
        filters:
        - name: RequestRateLimiter
          args:
            redis-rate-limiter.replenishRate: 1
            redis-rate-limiter.burstCapacity: 3
            key-resolver: "#{@ipKeyResolver}"
      - id: bs-service-search
        uri: lb://BS-SERVICE-SEARCH
        predicates:
        - Path=/search/**
      - id: bs-service-order
        uri: lb://BS-SERVICE-ORDER
        predicates:
        - Path=/order/**
