spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.104.176.62:3306/bs_manager_db?characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
    initialSize: 10
    minIdle: 5
    maxActive: 120
    maxWait: 60000
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 500