spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: #你的数据库url
    username: #用户名
    password: #密码
    initialSize: 10
    minIdle: 5
    maxActive: 120
    maxWait: 60000
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 500